/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class FrameAplikasiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form FrameAplikasiSuhu
     */
    public FrameAplikasiSuhu() {
        initComponents();

        txtSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                // Perbolehkan angka, backspace, dan tanda titik untuk desimal
                if (!Character.isDigit(c) && c != '\b' && c != '.') {
                    evt.consume(); // Abaikan karakter yang tidak valid
                }
            }
        });
        txtSuhu.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                konversiOtomatis();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                konversiOtomatis();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                konversiOtomatis();
            }
        });

    }

    private void konversiOtomatis() {
        try {
            if (txtSuhu.getText().isEmpty()) {
                jTextField2.setText("");
                return;
            }

            // Ambil nilai suhu dari txtSuhu
            double suhuAwal = Double.parseDouble(txtSuhu.getText());
            String satuanAwal = "";
            String satuanTujuan = cbKonversi.getSelectedItem().toString();
            double suhuHasil = 0;

            // Tentukan satuan awal berdasarkan radiobutton yang dipilih
            if (rbCelcius.isSelected()) {
                satuanAwal = "Celcius";
            } else if (rbFahrenheit.isSelected()) {
                satuanAwal = "Fahrenheit";
            } else if (rbKelvin.isSelected()) {
                satuanAwal = "Kelvin";
            } else if (rbReamur.isSelected()) {
                satuanAwal = "Reamur";
            } else {
                jTextField2.setText("Pilih satuan suhu awal!");
                return;
            }

            // Lakukan konversi berdasarkan satuan awal dan tujuan
            switch (satuanAwal) {
                case "Celcius":
                    suhuHasil = konversiCelcius(suhuAwal, satuanTujuan);
                    break;
                case "Fahrenheit":
                    suhuHasil = konversiFahrenheit(suhuAwal, satuanTujuan);
                    break;
                case "Kelvin":
                    suhuHasil = konversiKelvin(suhuAwal, satuanTujuan);
                    break;
                case "Reamur":
                    suhuHasil = konversiReamur(suhuAwal, satuanTujuan);
                    break;
            }

            // Tampilkan hasil di jTextField2
            jTextField2.setText(String.format("%.2f", suhuHasil));
        } catch (NumberFormatException e) {
            jTextField2.setText("Masukkan angka valid!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSuhu = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        rbCelcius = new javax.swing.JRadioButton();
        rbFahrenheit = new javax.swing.JRadioButton();
        rbKelvin = new javax.swing.JRadioButton();
        rbReamur = new javax.swing.JRadioButton();
        cbKonversi = new javax.swing.JComboBox<>();
        btnKonversi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Suhu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Pilih Jenis Suhu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Pilih Jenis Konversi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Suhu Hasil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel4, gridBagConstraints);

        txtSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuhuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(txtSuhu, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jTextField2, gridBagConstraints);

        rbCelcius.setText("Celcius");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(rbCelcius, gridBagConstraints);

        rbFahrenheit.setText("Fahrenheit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(rbFahrenheit, gridBagConstraints);

        rbKelvin.setText("Kelvin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(rbKelvin, gridBagConstraints);

        rbReamur.setText("Reamur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(rbReamur, gridBagConstraints);

        cbKonversi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Kelvin", "Reamur" }));
        cbKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKonversiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(cbKonversi, gridBagConstraints);

        btnKonversi.setText("Konversi Suhu");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(btnKonversi, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuhuActionPerformed

    private void cbKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKonversiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKonversiActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        konversiSuhu();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKonversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAplikasiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAplikasiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAplikasiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAplikasiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAplikasiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonversi;
    private javax.swing.JComboBox<String> cbKonversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton rbCelcius;
    private javax.swing.JRadioButton rbFahrenheit;
    private javax.swing.JRadioButton rbKelvin;
    private javax.swing.JRadioButton rbReamur;
    private javax.swing.JTextField txtSuhu;
    // End of variables declaration//GEN-END:variables

    private void konversiSuhu() {
        try {
            // Ambil nilai suhu dari txtSuhu
            double suhuAwal = Double.parseDouble(txtSuhu.getText());
            String satuanAwal = "";
            String satuanTujuan = cbKonversi.getSelectedItem().toString();
            double suhuHasil = 0;

            // Tentukan satuan awal berdasarkan radiobutton yang dipilih
            if (rbCelcius.isSelected()) {
                satuanAwal = "Celcius";
            } else if (rbFahrenheit.isSelected()) {
                satuanAwal = "Fahrenheit";
            } else if (rbKelvin.isSelected()) {
                satuanAwal = "Kelvin";
            } else if (rbReamur.isSelected()) {
                satuanAwal = "Reamur";
            } else {
                jTextField2.setText("Pilih satuan suhu awal!");
                return;
            }

            // Lakukan konversi berdasarkan satuan awal dan tujuan
            switch (satuanAwal) {
                case "Celcius":
                    suhuHasil = konversiCelcius(suhuAwal, satuanTujuan);
                    break;
                case "Fahrenheit":
                    suhuHasil = konversiFahrenheit(suhuAwal, satuanTujuan);
                    break;
                case "Kelvin":
                    suhuHasil = konversiKelvin(suhuAwal, satuanTujuan);
                    break;
                case "Reamur":
                    suhuHasil = konversiReamur(suhuAwal, satuanTujuan);
                    break;
            }

            // Tampilkan hasil di jTextField2
            jTextField2.setText(String.format("%.2f", suhuHasil));
        } catch (NumberFormatException e) {
            jTextField2.setText("Masukkan angka valid!");
        }
    }

// Fungsi konversi dari Celcius
    private double konversiCelcius(double suhu, String ke) {
        switch (ke) {
            case "Fahrenheit":
                return (suhu * 9 / 5) + 32;
            case "Kelvin":
                return suhu + 273.15;
            case "Reamur":
                return suhu * 4 / 5;
            default:
                return suhu;
        }
    }

// Fungsi konversi dari Fahrenheit
    private double konversiFahrenheit(double suhu, String ke) {
        switch (ke) {
            case "Celcius":
                return (suhu - 32) * 5 / 9;
            case "Kelvin":
                return (suhu - 32) * 5 / 9 + 273.15;
            case "Reamur":
                return (suhu - 32) * 4 / 9;
            default:
                return suhu;
        }
    }

// Fungsi konversi dari Kelvin
    private double konversiKelvin(double suhu, String ke) {
        switch (ke) {
            case "Celcius":
                return suhu - 273.15;
            case "Fahrenheit":
                return (suhu - 273.15) * 9 / 5 + 32;
            case "Reamur":
                return (suhu - 273.15) * 4 / 5;
            default:
                return suhu;
        }
    }

// Fungsi konversi dari Reamur
    private double konversiReamur(double suhu, String ke) {
        switch (ke) {
            case "Celcius":
                return suhu * 5 / 4;
            case "Fahrenheit":
                return (suhu * 9 / 4) + 32;
            case "Kelvin":
                return (suhu * 5 / 4) + 273.15;
            default:
                return suhu;
        }
    }

}
